### PR TITLE
fixes `n` slice_min/max bug

### LINKED ISSUE #108: @slice_max only returning one row, despite no ties
Here's some cycling-flavored data for a reprex 😄 I'm on Julia v.1.10.4.

```julia
using DataFrames
using Tidier
#> (@v1.10) pkg> status DataFrames, Tidier
#> Status `~/.julia/environments/v1.10/Project.toml`
#>   [a93c6f00] DataFrames v1.6.1
#>   [f0413319] Tidier v1.4.0


df = DataFrame(
    :city => [
        "New York city, New York",
        "Chicago city, Illinois",
        "Portland city, Oregon",
        "Los Angeles city, California",
        "San Francisco city, California",
        "Washington city, District of Columbia",
        "Seattle city, Washington",
        "Philadelphia city, Pennsylvania",
        "Boston city, Massachusetts",
        "Minneapolis city, Minnesota",
        "Austin city, Texas",
        "Denver city, Colorado",
        "San Diego city, California",
        "Madison city, Wisconsin",
        "Oakland city, California"
    ],
    :total_commuters => [
        4007171,
        1318960,
        347260,
        1938625,
        500469,
        362204,
        419233,
        662522,
        362198,
        231240,
        540911,
        377214,
        715730,
        146715,
        215534,
    ],
    :bike_commuters => [
        48601,
        22449,
        21982,
        20495,
        19429,
        16647,
        14801,
        14397,
        8873,
        8465,
        8266,
        8181,
        7188,
        7186,
        6540,
    ]
)
```

Let's say that I want to pull the top 10 cities with the most bike commuters. I'd expect that I could use the `@slice_max` macro and do something simple like this:

``` julia
@slice_max(df, bike_commuters, n = 10)
```

However, this returns:
```julia
1×3 DataFrame
 Row │ city                     total_commuters  bike_commuters 
     │ String                   Int64            Int64          
─────┼──────────────────────────────────────────────────────────
   1 │ New York city, New York          4007171           48601
```

Returning a single row in spite of the `n` value is expected behavior if `with_ties = false` according to the docs, but the default should be `with_ties = true` and there are no obvious ties in this data. So I would actually expect the result to be this:

```julia
10×3 DataFrame
 Row │ city                               total_commuters  bike_commuters 
     │ String                             Int64            Int64          
─────┼────────────────────────────────────────────────────────────────────
   1 │ New York city, New York                    4007171           48601
   2 │ Chicago city, Illinois                     1318960           22449
   3 │ Portland city, Oregon                       347260           21982
   4 │ Los Angeles city, California               1938625           20495
   5 │ San Francisco city, California              500469           19429
   6 │ Washington city, District of Col…           362204           16647
   7 │ Seattle city, Washington                    419233           14801
   8 │ Philadelphia city, Pennsylvania             662522           14397
   9 │ Boston city, Massachusetts                  362198            8873
  10 │ Minneapolis city, Minnesota                 231240            8465
```

If I pop over to R with the same dataset, this _is_ the result I get from `df |> slice_max(bike_commuters, n = 10)`, even if I shuffle the dataset around such that the `bike_commuters` column is not already ordered descending. I would expect `@slice_max` in Julia to behave the same way in this case.

If I try other values of `n` with the `@slice_max` macro, I still get back the 1x3 DataFrame.

### PR DESCRIPTION
**Pull request by drizk1**
fixes #108

### CODE REVIEW

**Comment by drizk1** [comment]
Scrolling thru the epi handbook, I noticed `head` is used a few times, so I went ahead and put together a head macro. It defaults to 6 rows, and supports grouped and ungrouped dataframes

**Comment by kdpsingh** [comment]
Thanks for fixing this! I'm working through a bit of a backlog and then will review and merge. This is much much appreciated.

**Comment by kdpsingh** [comment]
Thanks again @drizk1. Will add `@head` for now. This is functionally very similar to `@slice_head()`, so we should really consider whether we want to keep both. We could change the defaults for `@slice_head()` to behave more like `@head()` as a potential alternative.

**Comment by drizk1** [comment]
Oh wow, I actually completely forgot about `@slice_head` when I put together `@head`. I think relying on just `@slice_head` would definitely be reasonable

**Pull request merged**
