### PR TITLE
fill, docstring, istypes, benchmark

### PR DESCRIPTION
**Pull request by drizk1**
- I was unable to get parse_across to support the predicate functions, so the is_type do not have much functionality right now but included are is_float, is_integer, is_string.

- fill_missing macro + docstring + example
- slice_sample macro + docstring + addended slice in user guide
- added a benchmarking file to the docs. it may totally miss the mark with delivery. I am happy to revise as needed.

### CODE REVIEW

**Comment by drizk1** [comment]
draft.

**Comment by drizk1** [comment]
Ready for review.

**Comment by kdpsingh** [comment]
Thank you for working on this! Will take a look this weekend. My VSCode is acting up right now.

**Comment by kdpsingh** [comment]
Nice job on fixing the doctests! I'll got through these next week. There's a lot in this PR, so I want to make sure we get each new macro/function right.

**Comment by drizk1** [comment]
Sounds good. Only thing I couldn't figure out was the doc test output for slice_sample because it shows a random set of rows. I tried setting a seed but that did not work either so I suppressed output w ;

**Comment by kdpsingh** [comment]
I have ideas on how to fix.

**Comment by kdpsingh** [comment]
No worries about the failing tests, has to do with dependencies. Will come back to this.

**Pull request merged**
