### PR TITLE
@separate, @unite, @summary

### PR DESCRIPTION
**Pull request by drizk1**
Update includes
`@separate`, `@unite` and `@summary` with docstring and examples 
`@summary` docstring - had to use ; because table was too wide and i couldnt  correctly copy width

### CODE REVIEW

**Comment by kdpsingh** [comment]
@drizk1 is this ready to merge from your standpoint?

**Comment by kdpsingh** [comment]
I can take a look at the docstring issue for `@summary` if that's all that's left.

**Comment by drizk1** [comment]
That would be awesome. I can't figure out how to reproduce the evaluated output because it omits the last column due to width so the expected won't match evaluated.

**Comment by kdpsingh** [comment]
We'll figure out the docstrings later - I merged this with the main branch and will merge this PR for now.

In a future update, we can considering making `@summary()` work with strings and categoricals.

**Comment by drizk1** [comment]
Incredible. I'll def start moving @summary towards that goal

**Pull request merged**
